pipeline{
    properties([
  parameters([
    string(name: 'DEPLOY_ENV', defaultValue: 'TESTING', description: 'The target environment', )
   ])
])
    agent any
    stages{
        stage("Choose Commit"){
            steps{
                 //input([message: "Commit:",parameters:[$class: 'TextParameterDefinition', defaultValue: "${GIT_COMMIT}", description: 'choose commit to deploy', name:"deployCommit"])
                 echo 'bla' //"${params.deployCommit}"
            }
        }
        stage("Show Comit"){
            steps{
                echo "bla..."
            }
        }
    }
}