pipeline {
    agent any
    parameters {
        string(name: 'DEPLOY_COMMIT', description: 'commit to deploy to website')
        //choice(name: 'TARGET', choices: ['One', 'Two', 'Three'], description: 'Choose Deployment Target')
    }
    stages {
        stage('Deploy static website files') {
            steps {
                withAWS(credentials:"aws", region:"eu-central-1"){
                    echo "Commit: ${params.DEPLOY_COMMIT}"
                    s3Copy(pathStyleAccessEnabled: true, fromBucket:"karaokemp-artifacts", fromPath:"/karaokemp-website/COMMIT-${DEPLOY_COMMIT}/frontend/**", toBucket:'karaokemp-website', toPath:'/')
                }
            }
        }
    }
}